import {FIREBASE_API, FIREBASE_AUTHDOMAIN, FIREBASE_PROJECTID, FIREBASE_BUCKET, FIREBASE_MSGSENDERID, FIREBASE_APPID, FIREBASE_MEASUREMENTID} from '@env';

const firebaseConfig = {
  apiKey: FIREBASE_API,
  authDomain: FIREBASE_AUTHDOMAIN,
  projectId: FIREBASE_PROJECTID,
  storageBucket: FIREBASE_BUCKET,
  messagingSenderId: FIREBASE_MSGSENDERID,
  appId: FIREBASE_APPID,
  measurementId: FIREBASE_MEASUREMENTID
};

export {firebaseConfig}